spring:
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@localhost:${spring.data.mongodb.port}/${spring.data.mongodb.database}?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: true
      username: oms
      password: oms20190211!
      #      database: vms
      port: 27017
      database: vms

server:
  port: 8080

springdoc:
  com:
    oms:
      swagger-ui:
        server:
          ip: localhost

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@localhost:${spring.data.mongodb.port}/${spring.data.mongodb.database}?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: true
      username: oms
      password: oms20190211!
      database: test
      port: 27017